name: astral-core
version: '${version}'
main: org.dice.astralcore.Main
api-version: '1.20'
load: STARTUP
authors: [Boris Duque]
description: Core for Astral Server
website: https://github.com/bgduque
commands:
  s:
    description: Survival Game mode
    usage: /s
    permission: gm.survival
  sp:
    description: Spectator Game Mode
    usage: /sp
    permission: gm.spectator
  c:
    description: Creative Game mode
    usage: /c
    permission: gm.creative
  v:
    description: Vanish command
    usage: /v
    permissions:
      v.use:
        description: Allow to use the command
        default: op
      v.see:
        description: Allow to see the vanished administrators
        default: op
  heal:
    description: Heal command
    usage: /heal
    permission: a.heal
  fly:
    description: Flight mode On/Off
    usage: /fly
    permission: a.fly