name: astral-core
version: '${version}'
main: org.dice.astralcore.Main
api-version: '1.20'
load: STARTUP
authors: [Boris Duque]
description: Core for Astral Server
website: https://github.com/bgduque
commands:
  s:
    description: Survival Game mode
    usage: /s
    permission: gm.survival
  sp:
    description: Spectator Game Mode
    usage: /sp
    permission: gm.spectator
